spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tour
    username: root
    password: example
    initialization-mode: never

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    generate:-ddl: false
